# Generated by Django 4.1.4 on 2023-05-02 08:09

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()])),
                ('password', models.CharField(help_text='your password must contain at least 8 character and a mix of letters,numbers and symbols', max_length=100)),
            ],
        ),
    ]
