# Generated by Django 4.1.4 on 2023-05-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgdata',
            fields=[
                ('Index', models.IntegerField(primary_key=True, serialize=False)),
                ('organization_id', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('founded', models.IntegerField(max_length=4)),
                ('industry', models.CharField(max_length=255)),
                ('number_of_employee', models.IntegerField()),
            ],
        ),
    ]
