# Generated by Django 4.1.4 on 2023-05-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_orgdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgdata',
            name='founded',
            field=models.IntegerField(),
        ),
    ]
