# Generated by Django 4.1.4 on 2023-05-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_orgdata_founded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('inc_name', models.CharField(max_length=255)),
                ('proprietor_name', models.CharField(max_length=255)),
                ('meter_measurement', models.FloatField()),
                ('diff_units', models.FloatField()),
                ('avg_unit', models.FloatField()),
                ('power_utility_index', models.IntegerField()),
                ('power_station_name', models.CharField(max_length=255)),
                ('usage_type', models.CharField(max_length=255)),
                ('csi_index', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Orgdata',
        ),
    ]
