# Generated by Django 4.1.4 on 2023-05-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_meter_delete_orgdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='id',
        ),
        migrations.AlterField(
            model_name='meter',
            name='serial_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
