# Generated by Django 4.1.4 on 2023-05-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_remove_meter_id_alter_meter_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='csi_index',
            field=models.IntegerField(default=0),
        ),
    ]
